### ISSUE TITLE
simple chat text search not possible ?

### ISSUE THREAD

**Issue by johenkel** [SimonOrJ/CoreProtect-Lookup-Web-Interface#31] opened 2020-09-23 23:44 UTC
When leaving Users blank and only adding a Keyword while enabling chat & commands, the search result list will show all chat.

Is is supposed to do that or is there a way to search for a keyword in chat/command ?

( current version : CoreProtect Lookup Web Interface v1.0.0-pre2  )

**Comment by chuushi** [comment] 2020-11-30 20:02
Duplicate of #30

**Closed as completed by chuushi** 2020-11-30 20:02 UTC
